### ISSUE TITLE
unable to install it

### ISSUE THREAD

**Issue by limmeridge** [ataraxus/meshdoxer#1]
Hi, here there are the problems I found when trying to run the script.

1. If I start without docker installed in my system. This is what I get after running the script:

sudo: docker: command not found

2. If I install docker before running the script I get:

Unable to find image 'meshdoxer:latest' locally
Pulling repository docker.io/library/meshdoxer
docker: Error: image library/meshdoxer:latest not found.

3. If instead of running the script I copy every step in my terminal, it seems to work fine, but after the run command ( sudo docker run -ti --rm --name meshdoxer     -e DISPLAY=$DISPLAY    -v /tmp/.X11-unix:/tmp/.X11-unix    -v $(pwd)/exchange:/home/meshmixer/exchange   meshdoxer), I get:

xhost:  unable to open display ":0"

I don't know what else to try

**Comment by ataraxus** [comment]
Hey, sorry that my Script is not working for you as easy as for me. 

Could you tell me what exact distro you use. I just tested on the latest Ubuntu LTS. 

Also please run the script like so : `bash -x meshdoxer.sh` and paste me the output.

**Comment by limmeridge** [comment]
Hi, thanks for getting back.
I'm using Ubuntu 16.04.1 LTS, which I just installed yesterday. When I run the script this is what I get>
 bash -x meshdoxer.sh
- '[' 0 -ge 1 ']'
- run
  ++ pwd
- sudo docker run -ti --rm --name meshdoxer -e DISPLAY=:0 -v /tmp/.X11-unix:/tmp/.X11-unix -v /home/teresa/meshmixer/meshdoxer-master/exchange:/home/meshmixer/exchange meshdoxer
  [sudo] password for teresa: 
  Sorry, try again.
  [sudo] password for teresa: 
  Unable to find image 'meshdoxer:latest' locally
  Pulling repository docker.io/library/meshdoxer
  docker: Error: image library/meshdoxer:latest not found.
  See 'docker run --help'.

**Comment by ataraxus** [comment]
Hey so, it looks like you did't run the install routine: `./meshdoxer.sh install` 
I now included it by default so the next one will hopefully not struggle. 
I tested it with a fresh VM and it worked as expected
please do a 'git pull' and run `/meshdoxer.sh` again. 

Thanks for your feedback!

**Comment by limmeridge** [comment]
You're right!, now  installation worked, but I still get the same error when I try to run it>

xhost: unable to open display ":0"

**Comment by ataraxus** [comment]
could you again give me the full output with `bash -x ./meshdoxer.sh`

**Comment by ataraxus** [comment]
also in which environment are you using this script. it needs to be executed on a system with a Desktop installed. so if you have a headless VM it wont work.

**Comment by limmeridge** [comment]
I am using it in a normal distribution installed in my desktop with unity, is this what you mean. 
I get the same output as before:
- '[' 0 -ge 1 ']'
- run
  ++ pwd
- sudo docker run -ti --rm --name meshdoxer -e DISPLAY=:0 -v /tmp/.X11-unix:/tmp/.X11-unix -v /home/teresa/meshmixer/meshdoxer-master/exchange:/home/meshmixer/exchange meshdoxer
  [sudo] password for teresa: 
  xhost:  unable to open display ":0"

**Comment by ataraxus** [comment]
this is really strange :cry: 
basically what I'm doing is mounting your X server into the container so it can use it for displaying meshmixer... 

it seems that this is failing so that X is not available in the container. 
please give me the output of `ls -l /tmp/.X11-unix`

**Comment by limmeridge** [comment]
:( sorry for the trouble. My ubuntu seems to work fine however.

This is the output:
total 0

**Comment by ataraxus** [comment]
Just in case you are not running the experimental unity with mir, or something with wayland ;) 

lets see where your X has its port: 

`sudo lsof -U | grep  Xorg`

**Comment by limmeridge** [comment]
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
      Output information may be incomplete.
lsof: WARNING: can't stat() fuse.sshfs file system /home/teresa/odyssey
      Output information may be incomplete.
Xorg        996             root    1u  unix 0xffff8800bb956180      0t0  17345 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root    3u  unix 0xffff8800bb956540      0t0  17346 /tmp/.X11-unix/X0 type=STREAM
Xorg        996             root    4u  unix 0xffff88022f881680      0t0  19459 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root    6u  unix 0xffff8800bb957800      0t0  17357 type=STREAM
Xorg        996             root   20u  unix 0xffff8800bb956900      0t0  17387 type=STREAM
Xorg        996             root   31u  unix 0xffff880208a34740      0t0  39825 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   32u  unix 0xffff88022f85a580      0t0  19342 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   33u  unix 0xffff8800bb758780      0t0  25856 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   34u  unix 0xffff880208a34ec0      0t0  39827 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   35u  unix 0xffff8800bc2b7800      0t0  13268 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   36u  unix 0xffff88022f85e540      0t0  13283 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   37u  unix 0xffff8800bbd10780      0t0  13286 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   38u  unix 0xffff8800bbd12580      0t0  13292 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   39u  unix 0xffff8800bbd13c00      0t0  13296 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   40u  unix 0xffff8800bb758f00      0t0  21912 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   41u  unix 0xffff8800bbd17800      0t0  22637 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   42u  unix 0xffff8800bbd16180      0t0  23575 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   43u  unix 0xffff8800bbd14740      0t0  25604 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   44u  unix 0xffff880230e17bc0      0t0  20225 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   45u  unix 0xffff880230e14ec0      0t0  20228 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   46u  unix 0xffff8800bb576540      0t0  23760 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   47u  unix 0xffff880231200b40      0t0  23765 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   48u  unix 0xffff8802154183c0      0t0  21870 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   49u  unix 0xffff8800bc311680      0t0  20382 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   50u  unix 0xffff8800bb75cec0      0t0  20453 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   51u  unix 0xffff880231206900      0t0  22768 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   52u  unix 0xffff880231203480      0t0  22772 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   53u  unix 0xffff8802312012c0      0t0  22773 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   54u  unix 0xffff8800ab1ca580      0t0  22042 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   55u  unix 0xffff880208a36900      0t0  38539 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   56u  unix 0xffff880208a31a40      0t0  38541 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   57u  unix 0xffff880208a32580      0t0  46192 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   58u  unix 0xffff8801fe33cb00      0t0  33683 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   59u  unix 0xffff8801fe33d640      0t0  25386 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   60u  unix 0xffff8801fe338000      0t0  38734 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   61u  unix 0xffff8801fe33ecc0      0t0  50224 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   62u  unix 0xffff88012df5fbc0      0t0 745828 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   63u  unix 0xffff8801ebd7bfc0      0t0 745831 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   64u  unix 0xffff8801ee2721c0      0t0 266776 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   66u  unix 0xffff88022f885640      0t0  48842 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   68u  unix 0xffff880208a37440      0t0  91026 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   71u  unix 0xffff88005b992940      0t0 191948 @/tmp/.X11-unix/X0 type=STREAM
Xorg        996             root   72u  unix 0xffff88019da47800      0t0 191950 @/tmp/.X11-unix/X0 type=STREAM

**Comment by ataraxus** [comment]
ok sorry I'm out of ideas. your xserver tells us it connects to:
`Xorg 996 root 3u unix 0xffff8800bb956540 0t0 17346 /tmp/.X11-unix/X0 type=STREAM`
which i'm expecting... 
but your ´ls -l /tmp/.X11-unix´ tells us its missing. it should tell us:

```
ls -l /tmp/.X11-unix
insgesamt 0
srwxrwxrwx 1 root root 0 Nov  9 20:21 X0
```

have you tried to turn it off and on again? :joy:

**Comment by limmeridge** [comment]
don't worry, I will try to figure it out. Thanks so much for the help!

**Comment by ataraxus** [comment]
okay, i'll close this issue then. good luck!!!
